In [7]:
%pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\b8-01\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\b8-01\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd
import matplotlib.pyplot as plt

In [23]:
happy_life = pd.read_excel(r'D:\kimomin\DataAnalysis\happy\대한민국행복지도_삶의만족도.xlsx',engine='openpyxl')
happy_health = pd.read_excel(r'D:\kimomin\DataAnalysis\happy\대한민국행복지도_건강.xlsx',engine='openpyxl')
happy_safe = pd.read_excel(r'D:\kimomin\DataAnalysis\happy\대한민국행복지도_안전.xlsx',engine='openpyxl')
happy_environ = pd.read_excel(r'D:\kimomin\DataAnalysis\happy\대한민국행복지도_환경.xlsx',engine='openpyxl')
happy_econo = pd.read_excel(r'D:\kimomin\DataAnalysis\happy\대한민국행복지도_경제.xlsx',engine='openpyxl')
happy_edu = pd.read_excel(r'D:\kimomin\DataAnalysis\happy\대한민국행복지도_교육.xlsx',engine='openpyxl')
happy_relation = pd.read_excel(r'D:\kimomin\DataAnalysis\happy\대한민국행복지도_관계및사회참여.xlsx',engine='openpyxl')
happy_leisure = pd.read_excel(r'D:\kimomin\DataAnalysis\happy\대한민국행복지도_여가.xlsx',engine='openpyxl')

In [24]:
life_merge = happy_life.groupby('시도')[['삶의 만족도']].mean()
life_merge.head()

         삶의 만족도
시도
강원도    0.619506
경기도    0.426023
경상남도   0.530794
경상북도   0.502223
광주광역시  0.484480

In [28]:
temp1 = happy_health.groupby('시도')[['평균']].mean()
temp2 = happy_safe.groupby('시도')[['평균']].mean()
temp3 = happy_environ.groupby('시도')[['평균']].mean()
temp4 = happy_econo.groupby('시도')[['평균']].mean()
temp5 = happy_edu.groupby('시도')[['평균']].mean()
temp6 = happy_relation.groupby('시도')[['평균']].mean()
temp7 = happy_leisure.groupby('시도')[['평균']].mean()

In [29]:
life_merge = pd.merge(life_merge,temp1.rename(columns={'평균':'건강'}),on='시도')
life_merge = pd.merge(life_merge,temp2.rename(columns={'평균':'안전'}),on='시도')
life_merge = pd.merge(life_merge,temp3.rename(columns={'평균':'환경'}),on='시도')
life_merge = pd.merge(life_merge,temp4.rename(columns={'평균':'경제'}),on='시도')
life_merge = pd.merge(life_merge,temp5.rename(columns={'평균':'교육'}),on='시도')
life_merge = pd.merge(life_merge,temp6.rename(columns={'평균':'관계'}),on='시도')
life_merge = pd.merge(life_merge,temp7.rename(columns={'평균':'여기'}),on='시도')

In [30]:
life_merge

,삶의 만족도,건강_x,건강_y,안전,환경,경제,교육,관계,여기
시도,,,,,,,,,
강원도,0.619506,0.329506,0.329506,0.548000,0.639839,0.386861,0.488533,0.563122,0.632750
경기도,0.426023,0.353952,0.353952,0.325255,0.557977,0.468926,0.668619,0.601532,0.377561
경상남도,0.530794,0.312722,0.312722,0.475561,0.735600,0.325017,0.624022,0.395378,0.463750
경상북도,0.502223,0.264114,0.264114,0.484835,0.614265,0.303355,0.428252,0.402183,0.490804
광주광역시,0.484480,0.632300,0.632300,0.266440,0.607480,0.387380,0.689680,0.637800,0.454980
대구광역시,0.363988,0.482325,0.482325,0.358429,0.552500,0.393975,0.585838,0.407486,0.234925
대전광역시,0.407580,0.663580,0.663580,0.206780,0.582380,0.416260,0.840780,0.510820,0.347960
부산광역시,0.362081,0.511906,0.511906,0.404875,0.448719,0.438038,0.504594,0.294719,0.153587
서울특별시,0.490972,0.569532,0.569532,0.552256,0.470712,0.532820,0.399412,0.390656,0.286732
세종특별자치시,0.907700,0.232000,0.232000,0.157800,0.652400,0.511900,0.587000,0.673700,0.447800
울산광역시,0.471980,0.420040,0.420040,0.477060,0.393440,0.642580,0.763240,0.676440,0.418420
인천광역시,0.411480,0.339620,0.339620,0.421020,0.515020,0.410820,0.502920,0.504920,0.244590
전라남도,0.547709,0.424732,0.424732,0.565195,0.700573,0.202668,0.420019,0.481323,0.658668
전라북도,0.608193,0.421300,0.421300,0.410914,0.670586,0.196543,0.446936,0.487464,0.667900
제주특별자치도,0.711300,0.253700,0.253700,0.446100,0.684200,0.425000,0.646800,0.610700,0.694800
충청남도,0.553100,0.347433,0.347433,0.481313,0.558173,0.402893,0.648047,0.448720,0.625347
충청북도,0.410100,0.401064,0.401064,0.573155,0.466045,0.484755,0.592409,0.372782,0.702891